server:
  port: 8091

msg: Testing Greet API from config Server.


spring:   
  boot:
    admin:
      client:
        url: http://localhost:1111/
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
